// <auto-generated />
using System;
using Kutuphane.Rest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kutuphane.Rest.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20220908144619_InitialDatabase")]
    partial class InitialDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Kutuphane.Rest.Models.Durum", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Durums");
                });

            modelBuilder.Entity("Kutuphane.Rest.Models.Kitap", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BasimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurumID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SayfaSayisi")
                        .HasColumnType("int");

                    b.Property<string>("Türü")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YayinEviId")
                        .HasColumnType("int");

                    b.Property<string>("Yazari")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DurumID");

                    b.HasIndex("YayinEviId");

                    b.ToTable("Kitaps");
                });

            modelBuilder.Entity("Kutuphane.Rest.Models.KitapHareket", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Hareket")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HareketYonu")
                        .HasColumnType("int");

                    b.Property<int>("KitapID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("UyeBilgileriID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KitapID");

                    b.HasIndex("UyeBilgileriID");

                    b.ToTable("KitapHarekets");
                });

            modelBuilder.Entity("Kutuphane.Rest.Models.UyeBilgileri", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Admin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("UyeBilgileris");
                });

            modelBuilder.Entity("Kutuphane.Rest.Models.YayinEvi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("YayınEvis");
                });

            modelBuilder.Entity("Kutuphane.Rest.Models.Kitap", b =>
                {
                    b.HasOne("Kutuphane.Rest.Models.Durum", "Durum")
                        .WithMany("Kitaps")
                        .HasForeignKey("DurumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kutuphane.Rest.Models.YayinEvi", "YayinEvi")
                        .WithMany("Kitaps")
                        .HasForeignKey("YayinEviId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Durum");

                    b.Navigation("YayinEvi");
                });

            modelBuilder.Entity("Kutuphane.Rest.Models.KitapHareket", b =>
                {
                    b.HasOne("Kutuphane.Rest.Models.Kitap", "Kitap")
                        .WithMany("KitapHarekets")
                        .HasForeignKey("KitapID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kutuphane.Rest.Models.UyeBilgileri", "UyeBilgileri")
                        .WithMany("KitapHarekets")
                        .HasForeignKey("UyeBilgileriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kitap");

                    b.Navigation("UyeBilgileri");
                });

            modelBuilder.Entity("Kutuphane.Rest.Models.Durum", b =>
                {
                    b.Navigation("Kitaps");
                });

            modelBuilder.Entity("Kutuphane.Rest.Models.Kitap", b =>
                {
                    b.Navigation("KitapHarekets");
                });

            modelBuilder.Entity("Kutuphane.Rest.Models.UyeBilgileri", b =>
                {
                    b.Navigation("KitapHarekets");
                });

            modelBuilder.Entity("Kutuphane.Rest.Models.YayinEvi", b =>
                {
                    b.Navigation("Kitaps");
                });
#pragma warning restore 612, 618
        }
    }
}
